# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1216, 841)
        self.openButton = QtWidgets.QPushButton(Form)
        self.openButton.setGeometry(QtCore.QRect(60, 270, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.openButton.setFont(font)
        self.openButton.setObjectName("openButton")
        self.videoLabel = QtWidgets.QLabel(Form)
        self.videoLabel.setGeometry(QtCore.QRect(220, 60, 921, 641))
        self.videoLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.videoLabel.setLineWidth(5)
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.openButton.setText(_translate("Form", "Open Video"))
